[telegram]
userbot = true
# Get your telegram api-key from @botfather
api_key = "1425278481:AAHTCRS9agrLu4-TX5w-ax_IZ7NTkFz7L7s"
phone_number = "your_phone_number (empty if not in userbot mode)"
# Get client api keys from https://my.telegram.org
app_api_id = 1555704
app_api_hash = "f08030f122370b15dbeaefb39cb0f693"

[database]
sql_uri = "sqlite:///archivebot.db"

[logging]
sentry_enabled = false
sentry_token = ""

[download]
# Default for downloaded files
allowed_types = [
    "document",
    "photo",
]
target_dir = "/home/user/archivebot/"
